#! /usr/bin/env python
import requests
import zipfile
import shutil
import sys
import os

root = "A:/Projects/ahnaf-os/tests/root/"
# server = "https://github.com/ahnafalnafis/ahnaf-os/packages/"
server = "https://ahnafalnafis.github.io/ahnaf-os/packages/"
bin_dir = root + "bin/"


def download(url, path, pkgname, chunk_size=128):
    print(f"Downloading {pkgname}...")
    r = requests.get(url, stream=True)
    handler = open(path, 'wb')
    for chunk in r.iter_content(chunk_size=chunk_size):
        handler.write(chunk)


def extract(src, dst, pkgname):
    print(f"Unpacking {pkgname}...")
    with zipfile.ZipFile(src, 'r') as zip_ref:
        zip_ref.extractall(dst)


for pkgname in sys.argv[1:]:
    pkg = server + pkgname + ".zip"
    cache_dir = root + "cache/"
    file = cache_dir + pkgname + ".zip"
    try:
        download(pkg, file, pkgname)
        extract(file, cache_dir, pkgname)
        os.mkdir(f"{bin_dir}{pkgname}/")
        shutil.copy(f"{bin_dir}{pkgname}/", bin_dir)
        print(f"Successgully installed {pkgname}")
    except Exception as e:
        print(f"Package not found: {pkgname}")
        print(e)
