#! /usr/bin/env python
import os
import time
from colorama import init, Fore  # For colorize texts
from functions import read, write, verify
from dotenv import load_dotenv

# For colorize texts
init(convert=True)

# Loading etc/environment in order to get environment variables
load_dotenv("etc/environment")
paths = os.getenv("ENV").split(";")

logged_in = False
hostname = read("etc/hostname")
load_dotenv("etc/fstab")
root_dir = os.getenv("root_dir")
bin_dir = root_dir+"bin/"
binaries = os.listdir(bin_dir)


def main():
    while True:
        print("Welcome")
        username = input("Login: ")
        password = input("Password: ")
        verified = verify(username, password)
        logged_in = False
        while True:
            if verified:
                logged_in = True
                if logged_in:
                    cddir = read(
                        root_dir+"cache/cddir").replace("\\", "/")
                    if cddir == "None" or cddir == "":
                        cwd = "/"
                        os.chdir(root_dir)
                    else:
                        cwd = cddir
                        if not cwd.endswith("/"):
                            cwd += "/"
                        cwd = cwd.replace(root_dir, "/")
                        os.chdir(cddir)
                    command = input(
                        f"{Fore.YELLOW}{username}@{hostname}: {Fore.GREEN}{cwd} {Fore.RESET} \nψ ")  # ψ Ψ # λ #ε
                    if command == "shutdown":
                        write(f"{root_dir}cache/cddir", "None")
                        exit("Shutting Down...")

                    elif command == "reboot":
                        os.chdir(root_dir)
                        write(f"{root_dir}cache/cddir", "None")
                        print("Rebooting...")
                        time.sleep(3)

                        break

                    elif command == "exit":
                        logged_in = False
                        break

                    else:
                        if command == "":
                            continue
                        else:
                            found = False
                            scripts = list()
                            for path in paths:
                                path = path[0].replace(
                                    "/", root_dir) + path[1:]
                                for dir in path.split():
                                    for item in os.listdir(dir):
                                        scripts.append(item)
                                        if command.split()[0] in scripts:
                                            if os.path.isfile(f"{path}/{command.split()[0]}"):
                                                os.system(
                                                    f"python {path}/{command}")
                                                found = True
                                                break
                            else:
                                if not found:
                                    print(
                                        f"Command not found: {command.split()[0]}")
                else:
                    break

            else:
                print("Username or password is incorrect")


main()
